version: '3.8'
services:
  api_rest_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TheBestPassword
      POSTGRES_DB: restaurantDB
    ports:
      - '5432:5432'
  api_rest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api_rest_db
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - host=api_rest_db   
      - port=5432          
      - name=restaurantDB  
      - pass=TheBestPassword 
